# Generated by Django 2.0.5 on 2018-06-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zebradiary', '0002_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('ordering', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=25),
        ),
    ]
